name: INT Validate Tag

on:
  push:
    tags:
      - "INT-*"

permissions:
  contents: write

jobs:
  validate-int-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v5
        with: { node-version: "24" }
      - run: npm install --global @salesforce/cli
      - run: echo y | sf plugins install sfdx-git-delta
      - run: chmod +x scripts/*.sh
      - name: Auth INT
        run: |
          echo "${{ secrets.INT_SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias INT
      - name: Generate Delta
        run: |
          TO_SHA=${{ github.sha }}
          FROM_SHA=${{ github.event.before }}
          [ -z "$FROM_SHA" -o "$FROM_SHA" = "0000000000000000000000000000000000000000" ] && FROM_SHA=$(git rev-list --max-parents=0 HEAD)
          ./scripts/delta.sh $TO_SHA $FROM_SHA
      - name: Validate Deployment (tag)
        run: |
          if [ ! -s delta/package/package.xml ]; then exit 0; fi
          TEST_CLASSES=$(grep -oPm1 "(?<=<members>)[^<]+" delta/package/package.xml | grep Test || true)
          [ -z "$TEST_CLASSES" ] && TEST_CLASSES="SmokeTests"
          sf project deploy validate --manifest delta/package/package.xml --target-org INT --test-level RunSpecifiedTests --tests "$TEST_CLASSES"
