name: PROD Deployment

on:
  push:
    tags:
      - "prod-*"

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with: { node-version: "24" }
      - run: npm install --global @salesforce/cli
      - run: echo y | sf plugins install sfdx-git-delta
      - name: Auth PROD
        run: echo "${{ secrets.PROD_SFDX_AUTH_URL }}" > auth.txt && sf org login sfdx-url --sfdx-url-file auth.txt --alias PROD
      - name: Generate Delta from Preprod
        run: ./scripts/delta.sh ${{ github.sha }} ${{ github.event.before }}
      - name: Deploy to PROD
        run: |
          TEST_CLASSES=$(grep -oPm1 "(?<=<members>)[^<]+" delta/package/package.xml | grep "Test" || true)
          if [ -z "$TEST_CLASSES" ]; then TEST_CLASSES="SmokeTests"; fi
          sf project deploy start --manifest delta/package/package.xml --target-org PROD --test-level RunSpecifiedTests --tests "$TEST_CLASSES"
