name: Salesforce CI/CD

on:
  pull_request:
    branches: [ "sit", "int", "prod" ]
  push:
    branches: [ "sit", "int", "prod" ]

jobs:
  # ---------------- SIT ----------------
  validate-sit:
    if: ${{ github.ref_name == 'sit' }}
    name: Validate SIT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli@latest
      - name: Install Git Delta plugin
        run: echo y | sf plugins install sfdx-git-delta

      - name: Auth SIT
        env:
          SFDX_AUTH_URL: ${{ secrets.SIT_SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias SIT

      - name: Prepare Delta Directory
        run: mkdir -p delta

      - name: Generate Delta (PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: sf sgd source delta \
              --to ${{ github.event.pull_request.head.sha }} \
              --from ${{ github.event.pull_request.base.sha }} \
              --output delta

      - name: Generate Delta (Push)
        if: ${{ github.event_name == 'push' }}
        run: sf sgd source delta \
              --to ${{ github.sha }} \
              --from ${{ github.event.before }} \
              --output delta

      - name: Validate Deployment
        run: |
          TEST_CLASSES=$(grep -oPm1 "(?<=<members>)[^<]+" delta/package/package.xml | grep "Test" || true)
          if [ -z "$TEST_CLASSES" ]; then TEST_CLASSES="SmokeTests"; fi
          sf project deploy validate \
            --manifest delta/package/package.xml \
            --target-org SIT \
            --test-level RunSpecifiedTests \
            --tests "$TEST_CLASSES"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: delta-artifact-sit
          path: delta/
          retention-days: 30

  deploy-sit:
    needs: validate-sit
    if: ${{ needs.validate-sit.result == 'success' }}
    name: Deploy SIT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli@latest
      - name: Install Git Delta plugin
        run: echo y | sf plugins install sfdx-git-delta
      - name: Auth SIT
        env:
          SFDX_AUTH_URL: ${{ secrets.SIT_SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias SIT
      - uses: actions/download-artifact@v4
        with:
          name: delta-artifact-sit
      - name: Deploy to SIT
        run: sf project deploy start --manifest delta/package/package.xml --target-org SIT --ignore-conflicts

  # ---------------- INT ----------------
  validate-int:
    if: ${{ github.ref_name == 'int' }}
    name: Validate INT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli@latest
      - name: Install Git Delta plugin
        run: echo y | sf plugins install sfdx-git-delta
      - name: Auth INT
        env:
          SFDX_AUTH_URL: ${{ secrets.INT_SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias INT
      - name: Prepare Delta Directory
        run: mkdir -p delta
      - name: Generate Delta (PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: sf sgd source delta \
              --to ${{ github.event.pull_request.head.sha }} \
              --from ${{ github.event.pull_request.base.sha }} \
              --output delta
      - name: Generate Delta (Push)
        if: ${{ github.event_name == 'push' }}
        run: sf sgd source delta \
              --to ${{ github.sha }} \
              --from ${{ github.event.before }} \
              --output delta
      - name: Validate Deployment
        run: |
          TEST_CLASSES=$(grep -oPm1 "(?<=<members>)[^<]+" delta/package/package.xml | grep "Test" || true)
          if [ -z "$TEST_CLASSES" ]; then TEST_CLASSES="SmokeTests"; fi
          sf project deploy validate \
            --manifest delta/package/package.xml \
            --target-org INT \
            --test-level RunSpecifiedTests \
            --tests "$TEST_CLASSES"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: delta-artifact-int
          path: delta/
          retention-days: 30

  deploy-int:
    needs: validate-int
    if: ${{ needs.validate-int.result == 'success' }}
    name: Deploy INT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli@latest
      - name: Install Git Delta plugin
        run: echo y | sf plugins install sfdx-git-delta
      - name: Auth INT
        env:
          SFDX_AUTH_URL: ${{ secrets.INT_SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias INT
      - uses: actions/download-artifact@v4
        with:
          name: delta-artifact-int
      - name: Deploy to INT
        run: sf project deploy start --manifest delta/package/package.xml --target-org INT --ignore-conflicts

  # ---------------- PROD ----------------
  validate-prod:
    if: ${{ github.ref_name == 'prod' }}
    name: Validate PROD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli@latest
      - name: Install Git Delta plugin
        run: echo y | sf plugins install sfdx-git-delta
      - name: Auth PROD
        env:
          SFDX_AUTH_URL: ${{ secrets.PROD_SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias PROD
      - name: Prepare Delta Directory
        run: mkdir -p delta
      - name: Generate Delta (PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: sf sgd source delta \
              --to ${{ github.event.pull_request.head.sha }} \
              --from ${{ github.event.pull_request.base.sha }} \
              --output delta
      - name: Generate Delta (Push)
        if: ${{ github.event_name == 'push' }}
        run: sf sgd source delta \
              --to ${{ github.sha }} \
              --from ${{ github.event.before }} \
              --output delta
      - name: Validate Deployment
        run: |
          TEST_CLASSES=$(grep -oPm1 "(?<=<members>)[^<]+" delta/package/package.xml | grep "Test" || true)
          if [ -z "$TEST_CLASSES" ]; then TEST_CLASSES="SmokeTests"; fi
          sf project deploy validate \
            --manifest delta/package/package.xml \
            --target-org PROD \
            --test-level RunSpecifiedTests \
            --tests "$TEST_CLASSES"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: delta-artifact-prod
          path: delta/
          retention-days: 30

  deploy-prod:
    needs: validate-prod
    if: ${{ needs.validate-prod.result == 'success' }}
    name